// Product range. Each entry generates a page at /<category>/<slug>/
// Keep claims general ("available", "options") unless you have confirmed them with your supplier.

const commonWindowSpecs = [
  ['Glazing', 'Double-glazed as standard, triple-glazed on request'],
  ['Energy', 'Specified to Building Regulations Part L — U-value 1.4 W/m²K or better, or WER band B or above. A-rated options available'],
  ['Ventilation', 'Trickle vents fitted where Part F requires them'],
  ['Colours', 'White, cream, woodgrain foils and RAL colours including anthracite grey, black and Chartwell green'],
];

export const products = [
  /* ---------------- WINDOWS ---------------- */
  {
    slug: 'casement-windows',
    category: 'windows',
    name: 'Casement windows',
    short: 'The UK’s most fitted window. Side-hung, top-hung and fixed lights in any layout.',
    metaDescription: 'Made-to-measure uPVC casement windows supplied and fitted. Side-hung, top-hung and fixed layouts, A-rated glazing options and multipoint locking. Free survey and quote.',
    lead: 'A casement window is a frame divided into lights that are fixed, hinged at the side or hinged at the top. Because almost any combination is possible, it suits everything from 1930s semis to new-build extensions — and it is usually the most cost-effective way to replace old timber, aluminium or failed uPVC.',
    body: [
      'We design each casement around the room it serves. Bedrooms on upper floors normally need at least one opener large enough for escape, kitchens benefit from a top-hung vent that can stay open in the rain, and bathrooms usually take obscure glass. We note all of this at survey so the window you receive is right for the way you use the room — not just the right size.',
      'Profiles are available in chamfered (bevelled) or sculptured (rounded) styles, with a choice of colours on the outside and inside. Georgian or astragal bars, decorative glass and lead designs can be added if you are matching existing windows.',
    ],
    features: [
      ['Flexible layouts', 'Combine side-hung, top-hung and fixed lights to suit the opening and the room.'],
      ['Multipoint locking', 'Espagnolette locking with mushroom cams engages the frame at several points.'],
      ['Easy-clean hinges', 'Friction hinges with an easy-clean position let you reach the outside glass from indoors.'],
      ['Escape hinges', 'Egress hinges give a larger clear opening where a window is an escape route.'],
    ],
    specs: [['Opening types', 'Side-hung, top-hung, fixed — in any combination'], ...commonWindowSpecs, ['Security', 'Multipoint espagnolette locking, key-locking handles; PAS 24 tested options available']],
    goodFor: ['Most houses and bungalows', 'Kitchens and bathrooms (top-hung vents)', 'Replacing timber or aluminium casements'],
    options: ['Chamfered or sculptured profile', 'Georgian / astragal bars', 'Obscure or decorative glass', 'Child-safety restrictors', 'Fire-escape (egress) hinges', 'Trickle vents'],
    faqs: [
      ['Do casement windows open inwards or outwards?', 'Standard UK casements open outwards. If you need an inward-opening window — for example above a walkway — a tilt & turn window is usually the better choice.'],
      ['Can I have an escape window in a bedroom?', 'Yes. On first-floor habitable rooms we specify an opener with egress hinges so the clear opening meets Approved Document B (at least 0.33 m² and 450 mm wide and high, with the bottom of the opening no more than 1,100 mm above the floor).'],
    ],
    related: ['flush-casement-windows', 'tilt-and-turn-windows', 'bay-and-bow-windows'],
  },
  {
    slug: 'flush-casement-windows',
    category: 'windows',
    name: 'Flush casement windows',
    short: 'Sashes that sit flush in the frame for the look of traditional timber joinery.',
    metaDescription: 'uPVC flush casement windows with the look of traditional timber. Woodgrain and heritage colours, A-rated glazing options. Free survey and fixed written quote.',
    lead: 'In a flush casement the opening sashes sit level with the outer frame instead of overlapping it. That clean, flat face is how timber casements have been made in Britain for centuries — and it is why flush sash windows are now the first choice for period homes and for modern houses that want a crisper look.',
    body: [
      'Flush casements are built from deeper, more refined profiles than a standard casement, often with mechanical or timber-style corner joints and a woodgrain texture. They are particularly popular in anthracite grey, black, Chartwell green and cream, and dual colour (a heritage colour outside, white inside) is common.',
      'If you live in a conservation area, a flush casement is often the uPVC design most likely to be acceptable to a planning officer. We are happy to provide drawings and colour samples to support an application, but the decision always rests with your local planning authority.',
    ],
    features: [
      ['Timber-look finish', 'Flat face, slim sightlines and woodgrain textures for an authentic appearance.'],
      ['Heritage colours', 'Single or dual colour, with matching cills, bars and hardware.'],
      ['Same security', 'Multipoint locking and key-locking handles as standard casements.'],
      ['Low maintenance', 'No sanding or repainting — wash down a few times a year.'],
    ],
    specs: [['Opening types', 'Side-hung, top-hung, fixed'], ...commonWindowSpecs, ['Hardware', 'Butt hinge or friction hinge options, monkey-tail or contemporary handles']],
    goodFor: ['Period and character homes', 'Conservation areas (subject to planning)', 'Contemporary dark-frame designs'],
    options: ['Woodgrain or smooth finish', 'Externally fixed astragal bars', 'Butt hinges', 'Heritage handles and stays', 'Dual colour'],
    faqs: [
      ['Is a flush casement more expensive than a standard casement?', 'Yes — the profiles are larger and more involved to manufacture, so expect a higher price per window. Your survey quote shows both options side by side if you want to compare.'],
      ['Will flush casements be allowed in my conservation area?', 'It depends on your council and any Article 4 direction. We can provide drawings, specifications and samples for your application; the planning authority makes the decision.'],
    ],
    related: ['casement-windows', 'sash-windows', 'composite-doors'],
  },
  {
    slug: 'tilt-and-turn-windows',
    category: 'windows',
    name: 'Tilt & turn windows',
    short: 'Tilts in at the top for secure ventilation, swings fully inward for cleaning and escape.',
    metaDescription: 'uPVC tilt and turn windows supplied and fitted. Secure tilt ventilation, inward opening for easy cleaning — ideal for flats and upper floors. Free survey.',
    lead: 'One handle, two ways to open. Turn it 90° and the sash tilts inwards at the top for secure ventilation; turn it 180° and the whole sash swings into the room like a door. That makes tilt & turn the practical choice for flats, upper floors and anywhere the outside glass is hard to reach.',
    body: [
      'Because the sash opens inwards, nothing projects over a walkway, balcony or neighbour’s property. A large tilt & turn sash also gives a generous clear opening, so it is often used as an escape window.',
      'We check internal clearances at survey — curtains, blinds, radiators and window boards all need room for the sash to swing.',
    ],
    features: [
      ['Two opening modes', 'Tilt for ventilation, turn for cleaning, furniture access or escape.'],
      ['Clean from inside', 'Both faces of the glass are reachable without ladders.'],
      ['Nothing projects outside', 'Ideal next to paths, balconies and access decks.'],
      ['Mis-operation device', 'Prevents the sash being tilted and turned at the same time.'],
    ],
    specs: [['Opening types', 'Tilt-first or turn-first; side-hung turn, bottom-hung tilt'], ...commonWindowSpecs, ['Security', 'Perimeter multipoint locking; PAS 24 tested options available']],
    goodFor: ['Flats and high-rise buildings', 'Upper floors and loft rooms', 'Rooms next to walkways'],
    options: ['Tilt-first (child safety) operation', 'Restrictors', 'Integral blinds (selected sizes)', 'Triple glazing'],
    faqs: [
      ['Can tilt & turn windows be used as a fire escape?', 'Yes, provided the clear opening meets Approved Document B. We confirm this for each escape window at survey.'],
      ['Do they need special blinds?', 'Blinds must not obstruct the sash. Blinds fixed to the sash itself, or set back from the reveal, work well.'],
    ],
    related: ['casement-windows', 'sliding-windows', 'french-doors'],
  },
  {
    slug: 'sash-windows',
    category: 'windows',
    name: 'Sash windows',
    short: 'Vertical sliders that keep the proportions of a Victorian or Georgian box sash.',
    metaDescription: 'uPVC vertical sliding sash windows for Victorian, Edwardian and Georgian homes. Tilt-in sashes for cleaning, heritage details, A-rated glazing options. Free survey.',
    lead: 'A uPVC vertical sliding sash keeps the look of a traditional box sash — two sashes running past each other, run-through horns, deep bottom rail — without the rattles, draughts and repainting of old timber.',
    body: [
      'Modern sash windows run on spiral or constant-force balances rather than weights and cords, so they glide and stay where you leave them. Most systems let the sashes tilt inwards so you can clean both sides of the glass from inside.',
      'We match the pattern of the original windows: glazing bar layout, horn style, bottom-rail depth and colour. For listed buildings, replacement is rarely possible in uPVC — please check with your local authority before we survey.',
    ],
    features: [
      ['Authentic proportions', 'Run-through horns, deep bottom rails and Georgian bar patterns.'],
      ['Tilt-in cleaning', 'Sashes tilt inward so you can clean the outside glass safely.'],
      ['Smooth balances', 'Spiral or constant-force balances — no weights, cords or sticking.'],
      ['Draught-free', 'Brush pile and gasket seals end the rattle of old box sashes.'],
    ],
    specs: [['Operation', 'Vertical sliding, tilt-in for cleaning'], ...commonWindowSpecs, ['Security', 'Cam locks, sash stops / restrictors; PAS 24 tested options available']],
    goodFor: ['Victorian, Edwardian and Georgian houses', 'Replacing rotten timber sashes', 'Terraces and townhouses'],
    options: ['Georgian bars (2-over-2, 6-over-6 and others)', 'Run-through horns', 'Woodgrain finishes', 'Sash stops / restrictors', 'Heritage fittings in brass, chrome or black'],
    faqs: [
      ['Can uPVC sash windows go in a listed building?', 'Usually not. Listed building consent is needed for any window change and is rarely given for uPVC. Speak to your local authority conservation officer first.'],
      ['Will they still have trickle vents?', 'If your existing windows have trickle vents, Part F requires the replacements to have them too. Discreet vents can be fitted in the head of the frame.'],
    ],
    related: ['flush-casement-windows', 'bay-and-bow-windows', 'casement-windows'],
  },
  {
    slug: 'bay-and-bow-windows',
    category: 'windows',
    name: 'Bay & bow windows',
    short: 'Three, four or five facets that bring in light from several directions.',
    metaDescription: 'Replacement uPVC bay and bow windows with structural bay support poles where required. Casement, flush or sash styles. Free survey and written quote.',
    lead: 'A bay projects from the wall in angled facets — usually three at 45° or 30°; a bow uses four or more facets to form a gentle curve. Both add floor space and light, and both need careful surveying, because the frames often carry part of the structure above.',
    body: [
      'In many older homes the original timber bay frame is load-bearing, supporting a roof, a bedroom bay or brickwork above. uPVC frames are not designed to carry that load, so where needed we fit concealed bay support poles to transfer the weight to the cill or foundations before the old frames come out. Getting this wrong causes cracked frames and doors that will not close — it is one of the most important checks at our survey.',
      'Each facet can be any window style: casement, flush casement or sash. The angles are taken on site with a bay template rather than guessed.',
    ],
    features: [
      ['Structural survey', 'We check whether the existing bay carries load before quoting.'],
      ['Bay support poles', 'Concealed poles fitted inside the coupling joints where required.'],
      ['Any style per facet', 'Casement, flush or sash — matched to the rest of the house.'],
      ['Measured angles', 'Facet angles templated on site for a tight, square fit.'],
    ],
    specs: [['Configurations', '3-facet (45° / 30°), 4-, 5- and 6-facet bows'], ...commonWindowSpecs, ['Structure', 'Bay support poles where load-bearing; new cill or roof flashing if required']],
    goodFor: ['Front rooms of period houses', 'Adding light to dark lounges', 'Replacing failed timber bays'],
    options: ['Casement, flush or sash facets', 'Bay poles', 'Matching cills and board', 'Lead or tiled roof flashing repairs'],
    faqs: [
      ['How do I know if my bay is load-bearing?', 'If there is a room, roof or brickwork directly above the bay, assume it may be. We check on site and include support poles in the quote when they are needed.'],
      ['Do you replace the bay roof as well?', 'We can replace or re-flash small bay roofs as part of the job where needed. It is listed separately on your quote.'],
    ],
    related: ['casement-windows', 'sash-windows', 'flush-casement-windows'],
  },
  {
    slug: 'sliding-windows',
    category: 'windows',
    name: 'Horizontal sliding windows',
    short: 'Side-to-side sliders that never project inside or out.',
    metaDescription: 'uPVC horizontal sliding windows for walkways, balconies and tight spaces. No projecting sashes, double or triple glazing. Free survey and quote.',
    lead: 'A horizontal slider moves sideways on a track, so it takes up no space inside the room or outside the wall. That makes it useful beside walkways and balconies, over kitchen worktops and anywhere a swinging sash would get in the way.',
    body: [
      'Sliders are less common in UK houses than casements, but they solve real problems in the right place. We will tell you honestly at survey if a casement or tilt & turn would serve the room better.',
    ],
    features: [
      ['No projection', 'Nothing swings into the room or over a path.'],
      ['Wide views', 'Large glass areas with a single central meeting rail.'],
      ['Easy operation', 'Glides on a track — handy where you cannot reach far.'],
      ['Secure', 'Locking on the meeting rail with anti-lift features.'],
    ],
    specs: [['Operation', 'One or two sliding sashes, fixed or sliding outer panes'], ...commonWindowSpecs],
    goodFor: ['Walkways and balconies', 'Over worktops and sinks', 'Garden rooms'],
    options: ['2- or 3-pane layouts', 'Insect screens (selected systems)', 'Obscure glass'],
    faqs: [
      ['Are sliding windows as airtight as casements?', 'Modern sliders are well sealed, but compression-sealed casements and tilt & turns generally achieve better air-tightness. We will advise on the best option for the room.'],
    ],
    related: ['tilt-and-turn-windows', 'casement-windows', 'patio-doors'],
  },
  {
    slug: 'shaped-and-feature-windows',
    category: 'windows',
    name: 'Shaped & feature windows',
    short: 'Arches, gable apexes, circles and large fixed picture windows.',
    metaDescription: 'Bespoke shaped uPVC windows: arched, gable apex, circular and fixed picture windows. Templated on site and made to measure. Free survey.',
    lead: 'Arched heads, gable-end apexes, circular feature windows and large fixed panes are all possible in uPVC. Shaped frames are bent and welded to a template taken from your opening, so they follow the brickwork rather than approximating it.',
    body: [
      'Large fixed windows are often combined with opening casements below or beside them so that the room can still be ventilated, and so that the outside glass can be cleaned safely.',
    ],
    features: [
      ['Templated on site', 'We take a physical or digital template of the opening.'],
      ['Matches the rest', 'Same profile, colour and glass as your other windows.'],
      ['Opening combinations', 'Shaped tops can sit over side-hung or tilt & turn openers.'],
      ['Large fixed panes', 'Picture windows with toughened or laminated glass where required.'],
    ],
    specs: [['Shapes', 'Full and segmental arch, gothic, apex, circle, trapezium'], ...commonWindowSpecs],
    goodFor: ['Gable ends and stairwells', 'Period arches', 'Garden views'],
    options: ['Radial glazing bars', 'Decorative glass', 'Matching opening lights'],
    faqs: [
      ['Do shaped windows take longer?', 'Usually a little, because the frames are bent to a template. We confirm the lead time on your quote.'],
    ],
    related: ['casement-windows', 'bay-and-bow-windows', 'french-doors'],
  },

  /* ---------------- DOORS ---------------- */
  {
    slug: 'upvc-doors',
    category: 'doors',
    name: 'uPVC front & back doors',
    short: 'Reinforced uPVC entrance doors with multipoint locks and anti-snap cylinders.',
    metaDescription: 'uPVC front and back doors with multipoint locking, anti-snap cylinders and a choice of panels and glass. Supplied and fitted with a free survey.',
    lead: 'A uPVC door is the dependable, good-value choice for front and back entrances. Steel-reinforced frames, a full-height multipoint lock and an anti-snap cylinder give strong security, and there is a wide choice of panel designs, glass and colours.',
    body: [
      'Every door we fit comes with a multipoint lock that engages hooks and rollers along the locking edge, and we specify anti-snap cylinders rated to TS 007 3-star or SS 312 Diamond. Letterplates, spy-holes, knockers and numerals can be added, and low thresholds are available for step-free access.',
      'Side panels and top lights can be added to bring light into dark hallways. Any glass within 1,500 mm of the floor in a door or side panel is safety glass, as Approved Document K requires.',
    ],
    features: [
      ['Multipoint locking', 'Hook bolts and rollers along the full height of the door.'],
      ['Anti-snap cylinder', 'TS 007 3-star or SS 312 Diamond rated cylinders.'],
      ['Safety glass', 'Toughened or laminated glass in all critical locations.'],
      ['Low threshold', 'Step-free thresholds available for accessibility.'],
    ],
    specs: [['Styles', 'Panelled, half-glazed, fully glazed, with side panels and top lights'], ['Security', 'Multipoint lock, anti-snap cylinder; PAS 24 options available'], ['Energy', 'Meets Part L for replacement doors'], ['Colours', 'White, woodgrain foils and RAL colours']],
    goodFor: ['Back and side doors', 'Front doors on a budget', 'Utility rooms and garages'],
    options: ['Letterplate & knocker', 'Spy-hole / door chain', 'Side panels & top lights', 'Low threshold', 'Decorative glass'],
    faqs: [
      ['What is an anti-snap cylinder?', 'Lock-snapping is a common burglary method on older euro cylinders. Anti-snap cylinders are designed to break at a sacrificial line and still keep the lock secure. Look for TS 007 3-star or SS 312 Diamond ratings.'],
    ],
    related: ['composite-doors', 'stable-doors', 'french-doors'],
  },
  {
    slug: 'composite-doors',
    category: 'doors',
    name: 'Composite doors',
    short: 'Insulated core and a timber-look GRP skin — the premium front door.',
    metaDescription: 'Composite front doors with insulated cores, GRP skins and PAS 24 security options. Dozens of styles and colours, supplied and fitted with a free survey.',
    lead: 'A composite door combines several materials: a thick insulated core, a glass-reinforced plastic (GRP) skin with a realistic timber grain, and a uPVC or aluminium outer frame. The result looks like a painted hardwood door, insulates well and needs no repainting.',
    body: [
      'Composite doors are available in a large range of designs, from cottage-style ledged doors to contemporary slab doors with vertical glass. Many ranges offer a different colour inside and out at little or no extra cost.',
      'Most leading composite doors are tested to PAS 24 and many carry Secured by Design accreditation. If you need a particular standard — for example for insurance — tell us and we will specify a door that meets it.',
    ],
    features: [
      ['Solid feel', 'A thick, insulated core with a weighty, solid close.'],
      ['Timber look', 'GRP skin with natural grain texture that does not need painting.'],
      ['Colour choice', 'Wide palette, with dual colour available.'],
      ['High security', 'Multipoint lock and PAS 24 tested options as standard on most ranges.'],
    ],
    specs: [['Construction', 'Insulated core, GRP skin, uPVC or aluminium frame'], ['Security', 'Multipoint lock, anti-snap cylinder, PAS 24 / Secured by Design options'], ['Energy', 'Meets Part L for replacement doors'], ['Finish', 'Woodgrain GRP in solid colours, dual colour available']],
    goodFor: ['Front doors', 'Period and modern homes', 'Homes needing high security'],
    options: ['Side panels & top lights', 'Smart locks (selected ranges)', 'Chrome, black, gold or graphite hardware', 'House numbers & knockers'],
    faqs: [
      ['Are composite doors better than uPVC doors?', 'Composite doors are thicker and usually feel more solid, insulate slightly better and look more like timber. uPVC doors are more affordable. Both can be very secure when correctly specified and fitted.'],
      ['How long does a composite door take?', 'Composite doors are made to order. We confirm the lead time on your quote.'],
    ],
    related: ['upvc-doors', 'stable-doors', 'flush-casement-windows'],
  },
  {
    slug: 'french-doors',
    category: 'doors',
    name: 'French doors',
    short: 'A pair of glazed doors that open fully to the garden.',
    metaDescription: 'uPVC French doors for gardens and patios. Opening in or out, shoot-bolt and multipoint locking, side panels available. Free survey and quote.',
    lead: 'French doors are a pair of fully glazed doors that open from the centre with no post between them, giving a wide opening onto the garden. They suit openings from around 1,200 mm up to about 1,800 mm wide; side panels can make them wider still.',
    body: [
      'One leaf is the main door with the handle and multipoint lock; the other is the secondary leaf, held by shoot bolts top and bottom. Doors can open outwards (most common, saving room space) or inwards, and wide-opening restrictor stays hold them open in the wind.',
    ],
    features: [
      ['Wide clear opening', 'No centre mullion when both doors are open.'],
      ['Secure secondary leaf', 'Shoot bolts lock into head and threshold.'],
      ['Opening stays', 'Hold the doors open and protect hinges in the wind.'],
      ['Side panels', 'Extend the glass area across wider openings.'],
    ],
    specs: [['Opening', 'Outward or inward'], ['Security', 'Multipoint lock, shoot bolts, anti-snap cylinder'], ['Glass', 'Toughened / laminated safety glass, A-rated options'], ['Threshold', 'Standard or low threshold']],
    goodFor: ['Garden rooms and extensions', 'Replacing patio doors', 'Openings up to about 1.8 m'],
    options: ['Side panels', 'Georgian bars', 'Low threshold', 'Integral blinds'],
    faqs: [
      ['French doors or patio doors?', 'French doors open fully and suit narrower openings; sliding patio doors suit wider openings and do not need space to swing. We can show both at survey.'],
    ],
    related: ['patio-doors', 'bifold-doors', 'tilt-and-turn-windows'],
  },
  {
    slug: 'patio-doors',
    category: 'doors',
    name: 'Sliding patio doors',
    short: 'Large glass panels gliding on tandem rollers — no swing space needed.',
    metaDescription: 'uPVC in-line sliding patio doors with tandem rollers, anti-lift locking and large glass panels. 2, 3 and 4 panel options. Free survey and quote.',
    lead: 'In-line sliding patio doors use large glazed panels that slide past one another on tandem rollers. They give big views and wide access without needing room for doors to swing — ideal where furniture sits close to the glass.',
    body: [
      'Two-panel doors are most common; three- and four-panel configurations suit wider openings. Anti-lift blocks and multipoint hook locks stop sliding panels being lifted off their track.',
      'Over the years rollers and tracks wear. If your existing patio door has become heavy to slide, see our patio door repairs — replacement rollers often restore it for a fraction of the price of a new door.',
    ],
    features: [
      ['Big glass, slim frames', 'More view, less frame.'],
      ['Tandem rollers', 'Smooth, light sliding on stainless tracks.'],
      ['Anti-lift security', 'Hook locks and anti-lift blocks.'],
      ['No swing space', 'Keep furniture close to the glass.'],
    ],
    specs: [['Configurations', '2-, 3- and 4-panel'], ['Security', 'Multipoint hook locking, anti-lift'], ['Glass', 'Toughened safety glass, A-rated options'], ['Colours', 'White, woodgrain and RAL colours']],
    goodFor: ['Wide openings', 'Rooms with furniture near the doors', 'Replacing old aluminium patio doors'],
    options: ['3- and 4-panel layouts', 'Low threshold', 'Child-safety lock'],
    faqs: [
      ['Can you repair my existing patio door instead?', 'Often, yes. Worn rollers, damaged tracks and failed locks can usually be replaced. See our patio and bi-fold door repairs page.'],
    ],
    related: ['french-doors', 'bifold-doors', 'sliding-windows'],
  },
  {
    slug: 'bifold-doors',
    category: 'doors',
    name: 'Bi-fold doors',
    short: 'Panels fold and stack to one side to open a whole wall to the garden.',
    metaDescription: 'uPVC bi-fold doors for extensions and gardens. Panels fold to one or both sides, traffic door for everyday use, low threshold options. Free survey.',
    lead: 'Bi-fold doors are a series of hinged panels that fold concertina-style and stack to one or both sides, opening almost the full width of the frame. A traffic door lets you use one panel as an everyday door without folding the rest.',
    body: [
      'uPVC bi-folds are an affordable way to open up an extension. For very wide openings or where you want the slimmest possible frames, aluminium bi-folds may be the better choice — we will tell you honestly which suits your opening and budget.',
      'Bi-folds need a level, square structural opening and a properly supported head. We check both at survey.',
    ],
    features: [
      ['Wide opening', 'Panels stack neatly to open the whole width.'],
      ['Traffic door', 'One panel works as a normal door day to day.'],
      ['Fold inside or out', 'Choose the direction to suit your space.'],
      ['Low threshold', 'Options for a near-flush transition to the patio.'],
    ],
    specs: [['Configurations', '2 to 6 panels, stacking left, right or split'], ['Security', 'Multipoint locking, shoot bolts on each panel'], ['Glass', 'Toughened safety glass, A-rated options'], ['Threshold', 'Standard or low threshold']],
    goodFor: ['Kitchen and living extensions', 'Garden rooms', 'Openings around 2–4 m wide'],
    options: ['Traffic door', 'Low threshold', 'Integral blinds', 'Dual colour'],
    faqs: [
      ['How many panels do I need?', 'It depends on the opening width and how you want the doors to stack. As a guide, panels are usually between about 600 mm and 900 mm wide. We will draw the options at survey.'],
    ],
    related: ['patio-doors', 'french-doors', 'composite-doors'],
  },
  {
    slug: 'stable-doors',
    category: 'doors',
    name: 'Stable doors',
    short: 'Split top and bottom leaves — fresh air in, children and pets kept in.',
    metaDescription: 'uPVC and composite stable doors with independently opening top and bottom leaves and full multipoint locking. Supplied and fitted. Free survey.',
    lead: 'A stable door is split horizontally into two leaves that can open together as one door or separately. Open the top for fresh air and conversation while the bottom keeps children and pets inside — a favourite for kitchens and cottages.',
    body: [
      'Both leaves have their own locking, and the two are secured together when closed, so a stable door is as secure as a standard entrance door when correctly specified.',
    ],
    features: [
      ['Two independent leaves', 'Open the top, the bottom or both together.'],
      ['Full security', 'Multipoint locking on both leaves.'],
      ['Weather-sealed', 'Rebated meeting rail with weather bar.'],
      ['uPVC or composite', 'Available in both constructions.'],
    ],
    specs: [['Construction', 'uPVC or composite'], ['Security', 'Multipoint lock to each leaf, anti-snap cylinder'], ['Glass', 'Safety glass in the top leaf, optional'], ['Colours', 'White, woodgrain and RAL colours']],
    goodFor: ['Kitchen and utility doors', 'Cottages and farmhouses', 'Homes with pets or young children'],
    options: ['Glazed top leaf', 'Letterplate', 'Low threshold'],
    faqs: [
      ['Is a stable door secure?', 'Yes, when both leaves have their own multipoint locking and are secured together. We specify this as standard.'],
    ],
    related: ['upvc-doors', 'composite-doors', 'french-doors'],
  },
];

export const categories = {
  windows: {
    name: 'Windows',
    title: 'uPVC windows',
    metaDescription: 'Made-to-measure uPVC windows supplied and fitted: casement, flush casement, tilt & turn, sash, bay & bow, sliding and shaped windows. Free survey and written quote.',
    lead: 'Every window is made to measure from your survey and specified to current Building Regulations for energy, ventilation, safety glass and escape.',
  },
  doors: {
    name: 'Doors',
    title: 'uPVC & composite doors',
    metaDescription: 'uPVC and composite front doors, French doors, sliding patio doors, bi-folds and stable doors. Multipoint locking, anti-snap cylinders. Free survey.',
    lead: 'Entrance doors, garden doors and everything in between — with multipoint locks, anti-snap cylinders and safety glass as standard.',
  },
};

export const colours = [
  { name: 'White', hex: '#F4F4F1' },
  { name: 'Cream', hex: '#EDE6CF' },
  { name: 'Agate grey', hex: '#B4B2AA' },
  { name: 'Anthracite grey · RAL 7016', hex: '#383E42' },
  { name: 'Black', hex: '#1E1F21' },
  { name: 'Chartwell green', hex: '#8FA592' },
  { name: 'Golden oak', hex: '#A8692D' },
  { name: 'Rosewood', hex: '#5B2A22' },
];
