// Product range. Each entry generates a page at /<category>/<slug>/
// Keep claims general ("available", "options") unless you have confirmed them with your supplier.

const commonWindowSpecs = [
  ['Glazing', 'Double glazed as standard. Triple glazing available on request'],
  ['Energy', 'Meets Building Regulations Part L for replacement windows (U-value 1.4 W/m²K or better, or WER band B or above). A-rated options available'],
  ['Ventilation', 'Trickle vents fitted where Part F requires them, including wherever the old windows had them'],
  ['Safety glass', 'Toughened or laminated glass in critical locations, including any pane within 800 mm of the floor (Part K)'],
  ['Colours', 'White, cream, woodgrain foils and solid colours including anthracite grey (RAL 7016), black and Chartwell green'],
];

export const products = [
  /* ---------------- WINDOWS ---------------- */
  {
    slug: 'casement-windows',
    tag: "Suits most homes",
    chips: ["Side-hung", "Top-hung", "Fixed lights"],
    category: 'windows',
    name: 'Casement windows',
    short: 'Hinged and fixed panes in almost any layout. The standard window for most UK houses.',
    metaDescription: 'uPVC casement windows made to measure and fitted. Side-hung, top-hung and fixed lights, multipoint locks, escape hinges and A-rated glass. Free survey.',
    lead: 'A casement window is a frame split into panes, called lights, that are either fixed or hinged at the side or top. You can combine them in almost any layout, so casements suit 1930s semis, new-build extensions and most homes in between. They are usually the most cost-effective way to replace old timber, aluminium or tired uPVC.',
    body: [
      'We plan each window around the room it serves. An upper-floor bedroom usually needs an opener big enough to escape through. A kitchen benefits from a top-hung vent you can leave open in light rain. Bathrooms normally take obscure glass. We note all of this at survey, so the window suits how you use the room as well as the size of the opening.',
      'A few things are worth checking on any quote. Every opener should have a multipoint lock and a key-locking handle. Panes within 800 mm of the floor need safety glass. If your current windows have trickle vents, Part F says the new ones must have them too. And Part L asks for a U-value of 1.4 W/m²K or better, or a Window Energy Rating of band B or above.',
      'Profiles come in chamfered (bevelled) or sculptured (rounded) styles, in white, woodgrain or a solid colour, and the inside can be a different colour from the outside. Georgian or astragal bars, decorative glass and lead designs are available if you are matching existing windows. Our <a href="/guides/building-regulations-for-replacement-windows/">guide to Building Regulations for replacement windows</a> covers the rules in more detail.',
    ],
    features: [
      ['Any layout', 'Mix side-hung, top-hung and fixed lights to suit the opening, the view and the room.'],
      ['Multipoint locking', 'An espagnolette lock with mushroom cams grips the frame at several points along the sash.'],
      ['Easy-clean hinges', 'Friction hinges with an easy-clean position let you reach the outside glass from indoors.'],
      ['Escape hinges', 'Egress hinges open the sash wider, giving a bigger clear opening where the window is an escape route.'],
    ],
    specs: [['Opening types', 'Side-hung, top-hung and fixed, in any combination'], ...commonWindowSpecs, ['Security', 'Multipoint espagnolette locking, key-locking handles; PAS 24 tested options available']],
    goodFor: ['Most houses and bungalows', 'Kitchens and bathrooms (top-hung vents)', 'Replacing timber or aluminium casements'],
    options: ['Chamfered or sculptured profile', 'Georgian or astragal bars', 'Obscure or decorative glass', 'Child-safety restrictors', 'Egress (escape) hinges', 'Trickle vents', 'Dual colour'],
    faqs: [
      ['Do casement windows open inwards or outwards?', 'Standard UK casements open outwards. If a sash would swing out over a path, balcony or walkway, an inward-opening <a href="/windows/tilt-and-turn-windows/">tilt & turn window</a> is usually the better fit.'],
      ['Can I have an escape window in a bedroom?', 'Yes. Where a window is an escape route, usually in upper-floor bedrooms, we specify an opener with egress hinges so the clear opening meets Approved Document B. That means at least 0.33 m² of clear opening, at least 450 mm wide and 450 mm high, with the bottom of the opening no more than 1,100 mm above the floor. A replacement should never make escape harder than the window it replaces.'],
      ['What is the difference between chamfered and sculptured frames?', 'It is the shape of the frame edge. A chamfered profile has a flat, bevelled edge and looks crisp and modern. A sculptured profile has a rounded edge that looks closer to traditional timber. Performance is broadly the same, so choose the one that suits the house.'],
      ['Do replacement windows need Building Regulations approval?', 'Yes. Replacing a window is notifiable building work. It can be self-certified by an installer registered with a Competent Person Scheme such as FENSA or Certass, or approved by local authority building control. Your quote confirms how your installation will be certified. Keep the certificate, because a buyer’s solicitor will ask for it.'],
    ],
    related: ['flush-casement-windows', 'tilt-and-turn-windows', 'bay-and-bow-windows'],
  },
  {
    slug: 'flush-casement-windows',
    tag: "Timber look",
    chips: ["Sits flush", "Heritage colours", "Woodgrain"],
    category: 'windows',
    name: 'Flush casement windows',
    short: 'Sashes sit level with the frame, like timber joinery. Woodgrain and heritage colours.',
    metaDescription: 'uPVC flush casement windows with the flat face of traditional timber joinery. Woodgrain and heritage colours, multipoint locks and A-rated glass. Free survey.',
    lead: 'In a flush casement, each opening sash sits level with the outer frame instead of lapping over it. That flat face is how timber casements have been made in Britain for centuries. It suits period cottages and terraces, and modern homes that want a cleaner, more architectural look.',
    body: [
      'Flush casements use deeper, more detailed profiles than a standard casement. Many systems offer mechanical or timber-style corner joints and a woodgrain texture, so you do not see the welded corner line of a standard uPVC frame. Anthracite grey, black, Chartwell green and cream are popular, and dual colour (a heritage colour outside, white inside) is common.',
      'There are trade-offs. The frames are bulkier and cost more than a standard casement, and the sightlines can be slightly wider, which leaves a little less glass for the same opening. If you are replacing every window in the house, ask for both styles on your quote and compare them side by side.',
      'In a conservation area, a flush casement is often the uPVC design most likely to be accepted. We can supply drawings, specifications and colour samples to support an application, but the decision rests with your local planning authority. Check whether an Article 4 direction applies to your street before you order.',
    ],
    features: [
      ['Flat, timber-style face', 'Sashes sit level with the frame, with a woodgrain texture and neat corner joints.'],
      ['Heritage colours', 'Single or dual colour, with matching cills, bars and hardware.'],
      ['Same security', 'Multipoint locking and key-locking handles, as on a standard casement.'],
      ['Low maintenance', 'No sanding or repainting. Wash the frames down a few times a year.'],
    ],
    specs: [['Opening types', 'Side-hung, top-hung, fixed'], ...commonWindowSpecs, ['Hardware', 'Butt hinges or friction hinges; monkey-tail or contemporary handles']],
    goodFor: ['Period and character homes', 'Conservation areas (subject to planning)', 'Modern homes with dark frames'],
    options: ['Woodgrain or smooth finish', 'Externally fixed astragal bars', 'Butt hinges', 'Monkey-tail handles and stays', 'Dual colour'],
    faqs: [
      ['Is a flush casement more expensive than a standard casement?', 'Yes. The profiles are larger and take more work to make, so expect a higher price per window. If you are undecided, ask for both options on your quote so you can compare like for like.'],
      ['Will flush casements be allowed in my conservation area?', 'It depends on your council and whether an Article 4 direction covers your street. We can provide drawings, specifications and samples for your application. The planning authority makes the decision.'],
      ['What are butt hinges?', 'Butt hinges have a visible knuckle on the outside of the frame, like the hinges on old timber casements. They add to the traditional look. Friction hinges are hidden inside the frame and give an easy-clean position, so some people choose butt hinges at the front of the house and friction hinges elsewhere.'],
      ['Can I have a different colour inside and out?', 'Yes. Dual colour is common on flush casements, usually a heritage colour or woodgrain outside with white inside. Ask to see samples at survey, because colours look different on a small swatch than on a whole frame.'],
    ],
    related: ['casement-windows', 'sash-windows', 'composite-doors'],
  },
  {
    slug: 'tilt-and-turn-windows',
    tag: "Flats & upper floors",
    chips: ["Tilts to vent", "Opens inward"],
    category: 'windows',
    name: 'Tilt & turn windows',
    short: 'Tilts in to ventilate, swings in to clean. A practical choice for flats and upper floors.',
    metaDescription: 'uPVC tilt and turn windows made to measure. Tilt in to ventilate, open fully inward to clean or escape. Suits flats, upper floors and walkways. Free survey.',
    lead: 'A tilt & turn window has one handle and two opening positions. In one, the sash tilts in at the top for ventilation. In the other, it swings into the room on side hinges like a door. That makes it the practical choice for flats, upper floors and anywhere the outside glass is hard to reach.',
    body: [
      'Because the sash opens inwards, nothing projects over a walkway, balcony or a neighbour’s garden. A large tilt & turn sash also gives a generous clear opening, so it is often used as an escape window.',
      'Standard hardware turns first and tilts second as you move the handle. Tilt-first hardware swaps that order, so the first position is the safer tilt. It is worth choosing for children’s rooms, along with a lockable handle.',
      'The main trade-off is room space. When the sash turns, it swings into the room, so curtains, blinds, radiators, deep window boards and furniture all need clearance. We check this at survey. A tilt & turn also usually costs more than a casement of the same size, because the hardware is more involved.',
    ],
    features: [
      ['Two opening modes', 'Tilt for ventilation. Turn for cleaning, moving furniture in or escape.'],
      ['Clean from inside', 'Both faces of the glass are within reach without a ladder.'],
      ['Nothing projects outside', 'Suits openings beside paths, balconies and access decks.'],
      ['Mis-operation device', 'Stops the sash being tilted and turned at the same time.'],
    ],
    specs: [['Opening types', 'Turn-first or tilt-first; side-hung inward turn, bottom-hung inward tilt'], ...commonWindowSpecs, ['Security', 'Perimeter multipoint locking; PAS 24 tested options available']],
    goodFor: ['Flats and high-rise buildings', 'Upper floors and loft rooms', 'Rooms next to walkways or balconies'],
    options: ['Tilt-first (child safety) hardware', 'Lockable handles', 'Restrictors', 'Integral blinds (selected systems)', 'Triple glazing'],
    faqs: [
      ['Can tilt & turn windows be used as a fire escape?', 'Yes, if the clear opening meets Approved Document B. That means at least 0.33 m², at least 450 mm wide and 450 mm high, with the bottom of the opening no more than 1,100 mm above the floor. We check each escape window at survey.'],
      ['Do they need special blinds?', 'The blind must not block the sash as it swings in. Blinds fixed to the sash itself work well, as do blinds set far enough back from the reveal. Integral blinds inside the glass are available on selected systems.'],
      ['Is it safe to leave a tilt & turn on tilt?', 'The gap at the top is small and hard to reach from outside, so tilt is a safer way to ventilate than an open casement. It is still an open window. Close and lock it when you go out.'],
      ['Should I choose turn-first or tilt-first?', 'Turn-first is the standard arrangement and suits most rooms. Choose tilt-first where children could reach the handle, because a quick turn only tilts the sash rather than opening it fully. Lockable handles add another layer of protection.'],
    ],
    related: ['casement-windows', 'sliding-windows', 'french-doors'],
  },
  {
    slug: 'sash-windows',
    tag: "Victorian & Georgian",
    chips: ["Vertical slider", "Tilt-in cleaning"],
    category: 'windows',
    name: 'Sash windows',
    short: 'Vertical sliders in the proportions of a box sash. No rattles, cords or repainting.',
    metaDescription: 'uPVC sliding sash windows for Victorian, Edwardian and Georgian homes. Run-through horns, Georgian bars, tilt-in cleaning and A-rated glass. Free survey.',
    lead: 'A uPVC vertical sliding sash keeps the look of a traditional box sash, with two sashes sliding past each other, run-through horns and a deep bottom rail. It drops the rattles, draughts and repainting that come with old timber.',
    body: [
      'Modern sash windows run on spiral or constant-force balances rather than weights and cords, so they slide smoothly and stay where you leave them. On most systems the sashes tilt inwards, so you can clean both sides of the glass from inside.',
      'We match the details of your original windows, including the glazing bar layout, horn style, bottom-rail depth and colour. Measuring matters here. In many older houses the frame sits behind a rebate in the brickwork, so we measure from inside and out before we quote.',
      'Be realistic about the trade-offs. uPVC sashes have thicker frames and meeting rails than slim timber ones, and a sliding sash does not usually seal as tightly as a compression-sealed casement. In a listed building, replacement in uPVC is rarely allowed, so check with your local authority before booking a survey.',
    ],
    features: [
      ['Authentic proportions', 'Run-through horns, deep bottom rails and Georgian bar patterns.'],
      ['Tilt-in cleaning', 'Sashes tilt inwards so you can clean the outside glass from indoors.'],
      ['Balanced sashes', 'Spiral or constant-force balances replace weights and cords.'],
      ['Fewer draughts', 'Brush pile and gasket seals stop the rattle of old box sashes.'],
    ],
    specs: [['Operation', 'Vertical sliding; sashes tilt in for cleaning on most systems'], ...commonWindowSpecs, ['Security', 'Cam locks, sash stops or restrictors; PAS 24 tested options available']],
    goodFor: ['Victorian, Edwardian and Georgian houses', 'Replacing rotten timber sashes', 'Terraces and townhouses'],
    options: ['Georgian bars (2-over-2, 6-over-6 and others)', 'Run-through horns', 'Woodgrain finishes', 'Sash stops or restrictors', 'Fittings in brass, chrome or black'],
    faqs: [
      ['Can uPVC sash windows go in a listed building?', 'Usually not. Listed building consent is needed for any window change and is rarely given for uPVC. Speak to your local authority conservation officer before you go further.'],
      ['Will they still have trickle vents?', 'If your existing windows have trickle vents, Part F requires the replacements to have them too. Slim vents can be fitted in the head of the frame, where they are least noticeable.'],
      ['Can a sash window be an escape window?', 'It can, but it is harder. Only one sash opens at a time, so the clear opening is roughly half the window. An escape window needs at least 0.33 m² clear, at least 450 mm wide and 450 mm high, with the bottom of the opening no more than 1,100 mm above the floor. We check the size at survey and suggest options if it falls short.'],
      ['Should I restore my timber sashes instead?', 'If the timber is mostly sound, or the house is listed, restoration by a timber sash specialist may be the better route. uPVC makes most sense where the frames are rotten or you want to stop repainting.'],
    ],
    related: ['flush-casement-windows', 'bay-and-bow-windows', 'casement-windows'],
  },
  {
    slug: 'bay-and-bow-windows',
    tag: "Front rooms",
    chips: ["3–6 facets", "Bay support poles"],
    category: 'windows',
    name: 'Bay & bow windows',
    short: 'Three to six facets that catch light from several sides. Structure checked at survey.',
    metaDescription: 'Replacement uPVC bay and bow windows. We check whether the old bay carries load and fit support poles where needed. Casement, flush or sash facets. Free survey.',
    lead: 'A bay window projects from the wall in angled facets, usually three. A bow uses four or more shallower facets to form a gentle curve. Both add light and a little floor space, and both need careful surveying, because the old frames often carry part of the structure above.',
    body: [
      'In many older homes the original timber bay is load-bearing. It may support a bay roof, a bedroom bay or brickwork above. uPVC frames are not designed to carry that weight, so where it is needed we fit bay support poles inside the corner couplings to take the load down to the cill or brickwork below. They go in before the old frames come out. Skipping this step leads to cracked frames, sagging heads and sashes that will not close.',
      'Each facet can be a casement, flush casement or sash, matched to the rest of the house. The angles are measured on site with a bay template rather than assumed, because older bays are rarely perfectly square or symmetrical.',
      'Look at the roof and cill while you are planning. A leaking lead or tiled bay roof, or a cracked concrete cill, is best dealt with while the windows are out. Any extra work is listed separately on your quote.',
    ],
    features: [
      ['Structural check', 'We check whether the existing bay carries load before we quote.'],
      ['Bay support poles', 'Fitted inside the corner couplings where the bay is load-bearing.'],
      ['Any style per facet', 'Casement, flush casement or sash, matched to the rest of the house.'],
      ['Measured angles', 'Facet angles templated on site for a tight, square fit.'],
    ],
    specs: [['Configurations', '3-facet bays (typically 45° or 30°); 4-, 5- and 6-facet bows'], ...commonWindowSpecs, ['Structure', 'Bay support poles where the bay is load-bearing; new cill or roof flashing if required']],
    goodFor: ['Front rooms of period houses', 'Dark lounges that need more light', 'Replacing failed timber bays'],
    options: ['Casement, flush or sash facets', 'Bay support poles', 'Matching cills and window boards', 'Bay roof re-flashing or repair'],
    faqs: [
      ['How do I know if my bay is load-bearing?', 'If there is a room, a roof or brickwork directly above the bay, assume it may be. We check on site and include support poles in the quote when they are needed.'],
      ['Do you replace the bay roof as well?', 'We can replace or re-flash small lead or tiled bay roofs as part of the job where needed. Roof work is priced as a separate line on your quote.'],
      ['What is the difference between a bay and a bow window?', 'A bay usually has three facets set at a sharper angle, which gives a squarer projection. A bow has four or more narrower facets set at shallow angles, so it reads as a curve. Curved bows are common on 1930s semis.'],
    ],
    related: ['casement-windows', 'sash-windows', 'flush-casement-windows'],
  },
  {
    slug: 'sliding-windows',
    tag: "Tight spaces",
    chips: ["No projection", "2–3 panes"],
    category: 'windows',
    name: 'Horizontal sliding windows',
    short: 'Sashes slide sideways, so nothing swings in or out. Useful by walkways and over worktops.',
    metaDescription: 'uPVC horizontal sliding windows for walkways, balconies and kitchens. Sashes slide sideways, so nothing projects in or out. 2- and 3-pane layouts. Free survey.',
    lead: 'A horizontal sliding window moves sideways on a track, so it takes up no space inside the room or outside the wall. That makes it useful beside walkways and balconies, over kitchen worktops, and anywhere a swinging sash would get in the way.',
    body: [
      'Sliders are less common in UK houses than casements, but they make sense in a few specific places. They are also easier for anyone who struggles to lean across a deep worktop and push a sash open.',
      'There are trade-offs. Only part of the window opens at once, so the ventilation and escape opening is smaller than the frame size suggests. Most sliders seal with brush pile rather than compression gaskets, so they are generally less airtight than casements or tilt & turns. If another style would suit the room better, we will say so at survey.',
    ],
    features: [
      ['No projection', 'Nothing swings into the room or out over a path.'],
      ['Wide views', 'Large glass areas with a single meeting rail.'],
      ['Easy to reach', 'Slides on a track, which helps where you cannot reach far.'],
      ['Secure', 'Locks on the meeting rail, with anti-lift features to keep sashes in the track.'],
    ],
    specs: [['Operation', 'One or two sliding sashes, with fixed or sliding outer panes'], ...commonWindowSpecs],
    goodFor: ['Walkways and balconies', 'Over worktops and sinks', 'Garden rooms'],
    options: ['2- or 3-pane layouts', 'Insect screens (selected systems)', 'Obscure glass'],
    faqs: [
      ['Are sliding windows as airtight as casements?', 'Modern sliders are well sealed, but compression-sealed casements and tilt & turns generally achieve better air-tightness. We will advise on the best option for the room.'],
      ['Can a sliding window be used as a fire escape?', 'Only if the opening part alone meets Approved Document B. That means at least 0.33 m² clear, at least 450 mm wide and 450 mm high, with the bottom of the opening no more than 1,100 mm above the floor. Because only part of a slider opens, the frame has to be fairly large. For a bedroom escape window, a casement or tilt & turn is often simpler.'],
      ['How do I keep a sliding window running smoothly?', 'Vacuum grit out of the bottom track a few times a year, wipe it with a damp cloth and keep the drainage slots clear. If a sash still drags, the rollers may be worn. That is usually a repair rather than a new window.'],
    ],
    related: ['tilt-and-turn-windows', 'casement-windows', 'patio-doors'],
  },
  {
    slug: 'shaped-and-feature-windows',
    tag: "Bespoke shapes",
    chips: ["Arches", "Gable apex", "Picture windows"],
    category: 'windows',
    name: 'Shaped & feature windows',
    short: 'Arches, apexes, circles and picture windows. Templated to your opening.',
    metaDescription: 'Shaped uPVC windows templated to your opening. Arched heads, gable apexes, circles and large picture windows, matched to the rest of your windows. Free survey.',
    lead: 'Arched heads, gable-end apexes, circular feature windows and large fixed panes are all possible in uPVC. Shaped frames are bent or cut and welded to a template taken from your opening, so they follow the brickwork rather than approximating it.',
    body: [
      'Large fixed windows are usually combined with opening lights below or beside them. That way the room can still be ventilated, and the outside glass can be cleaned safely.',
      'Glass matters more on big panes. Any glass within 800 mm of the floor must be safety glass under Approved Document K, and large panes are often toughened or laminated for strength anyway. In a stairwell or a high gable, think about how the outside will be cleaned before you choose a fixed pane.',
      'Shaped windows usually take a little longer to make than standard ones, because each frame is made to its own template. Your quote confirms the lead time.',
    ],
    features: [
      ['Templated on site', 'We take a physical or digital template of the opening.'],
      ['Matches the rest', 'Same profile, colour and glass as your other windows.'],
      ['Opening combinations', 'Shaped tops can sit above side-hung or tilt & turn openers.'],
      ['Large fixed panes', 'Picture windows with toughened or laminated glass where required.'],
    ],
    specs: [['Shapes', 'Full and segmental arch, gothic arch, apex, circle, trapezium'], ...commonWindowSpecs],
    goodFor: ['Gable ends and stairwells', 'Arched openings in period homes', 'Rooms with a garden view'],
    options: ['Radial glazing bars', 'Decorative glass', 'Matching opening lights', 'Toughened or laminated glass'],
    faqs: [
      ['Do shaped windows take longer?', 'Usually a little, because the frames are made to a template of your opening. We confirm the lead time on your quote.'],
      ['Can a shaped window open?', 'Some can. A gentle segmental arch can often be made as an opener, but most arches, circles and apexes are fixed. We usually pair them with an opening casement or tilt & turn below, so the room can still be ventilated.'],
    ],
    related: ['casement-windows', 'bay-and-bow-windows', 'french-doors'],
  },

  /* ---------------- DOORS ---------------- */
  {
    slug: 'upvc-doors',
    tag: "Good value",
    chips: ["Multipoint lock", "Anti-snap cylinder"],
    category: 'doors',
    name: 'uPVC front & back doors',
    short: 'Reinforced entrance doors with multipoint locks. Anti-snap cylinders as standard.',
    metaDescription: 'uPVC front and back doors with multipoint locks and TS 007 3-star or SS 312 Diamond cylinders. Choice of panels, glass and colours. Free survey and quote.',
    lead: 'A uPVC door is the dependable, good-value choice for front, back and side entrances. A steel-reinforced frame, a full-height multipoint lock and an anti-snap cylinder make it hard to force, and there is a wide choice of panel designs, glass and colours.',
    body: [
      'Every door we fit has a multipoint lock that throws hooks, bolts or rollers into the frame along the locking edge. We specify anti-snap cylinders rated TS 007 3-star or SS 312 Diamond. Letterplates, spy-holes, knockers and numerals can be added, and low thresholds are available for step-free access.',
      'Side panels and top lights bring light into a dark hallway. Glass in the door, and in any side panel within 300 mm of it, must be safety glass up to 1,500 mm above the floor (Approved Document K). A replacement door also has to meet Part L, with a U-value of 1.4 W/m²K or better, or a Door Set Energy Rating of band B or above. Band C is allowed where the door is more than 60% glazed.',
      'Compared with a composite door, uPVC is lighter, thinner and usually cheaper. Both can be very secure when correctly specified and fitted. Our <a href="/guides/upvc-vs-composite-doors/">uPVC vs composite door guide</a> sets out the differences.',
    ],
    features: [
      ['Multipoint locking', 'Hooks, bolts or rollers engage the frame along the full height of the door.'],
      ['Anti-snap cylinder', 'Rated TS 007 3-star or SS 312 Diamond.'],
      ['Safety glass', 'Toughened or laminated glass wherever Part K requires it.'],
      ['Low threshold', 'A step-free threshold for wheelchairs, walking aids and pushchairs.'],
    ],
    specs: [['Styles', 'Panelled, half-glazed or fully glazed, with optional side panels and top lights'], ['Security', 'Multipoint lock, TS 007 3-star or SS 312 Diamond cylinder; PAS 24 options available'], ['Energy', 'Meets Part L for replacement doors (1.4 W/m²K or better, or DSER band B or above; band C where more than 60% glazed)'], ['Colours', 'White, woodgrain foils and RAL colours']],
    goodFor: ['Back and side doors', 'Front doors on a tighter budget', 'Utility rooms and garages'],
    options: ['Letterplate and knocker', 'Spy-hole or door chain', 'Side panels and top lights', 'Low threshold', 'Decorative glass'],
    faqs: [
      ['What is an anti-snap cylinder?', 'Lock snapping is a common way of breaking into doors fitted with older euro cylinders. An anti-snap cylinder is designed to break at a sacrificial line and keep the lock secure when attacked. Look for a TS 007 3-star or SS 312 Diamond rating, usually marked on the face of the cylinder.'],
      ['My door is hard to lock. Do I need a new one?', 'Usually not. A handle that needs force to lift often means the door has dropped or the gearbox is worn, and both can be fixed. See our <a href="/repairs/door-alignment/">door alignment repairs</a> before you replace a sound door.'],
      ['Can I have a level threshold?', 'Yes. A low threshold reduces the step at the door for wheelchairs, walking aids and pushchairs. It needs careful detailing to keep rain out, so we check the ground level and exposure outside at survey.'],
    ],
    related: ['composite-doors', 'stable-doors', 'french-doors'],
  },
  {
    slug: 'composite-doors',
    tag: "Premium front door",
    chips: ["Thick core", "PAS 24 options"],
    category: 'doors',
    name: 'Composite doors',
    short: 'A thick core behind a timber-look GRP skin. A solid, low-maintenance front door.',
    metaDescription: 'Composite front doors with a thick core, timber-grain GRP skin and multipoint locking. PAS 24 and Secured by Design options, dual colour. Free survey and quote.',
    lead: 'A composite door is built from several materials. A thick core, usually insulating foam or solid timber, sits behind a glass-reinforced plastic (GRP) skin with a timber grain, in a uPVC or aluminium frame. It looks like a painted hardwood door, insulates well and does not need repainting.',
    body: [
      'Designs range from cottage-style ledged doors to contemporary slab doors with vertical glass. Many ranges offer a different colour inside and out, so the hall side can match your interior.',
      'PAS 24 and Secured by Design options are available. If your insurer or lender asks for a particular standard, tell us before you order and we will specify a door that meets it. Whatever the range, check that the cylinder is rated TS 007 3-star or SS 312 Diamond.',
      'Composite doors are heavier than uPVC, so the frame and hinges have to be set up correctly to stop the door dropping over time. A dark door in full sun can also feel stiffer to lock on hot days as the materials expand. Adjustable hinges and keeps allow for this.',
    ],
    features: [
      ['Solid feel', 'A thick core gives a heavier, more solid close than a uPVC door.'],
      ['Timber look', 'A GRP skin with a grain texture that does not need painting.'],
      ['Colour choice', 'A wide palette, with a different colour inside and out on many ranges.'],
      ['Security options', 'Multipoint locking, with PAS 24 and Secured by Design options.'],
    ],
    specs: [['Construction', 'Thick core (insulating foam or solid timber, depending on the range), GRP skin, uPVC or aluminium frame'], ['Security', 'Multipoint lock, anti-snap cylinder; PAS 24 and Secured by Design options available'], ['Energy', 'Meets Part L for replacement doors (1.4 W/m²K or better, or DSER band B or above)'], ['Finish', 'Woodgrain GRP in solid colours; dual colour available']],
    goodFor: ['Main front doors', 'Period and modern homes', 'Homes needing a set security standard'],
    options: ['Side panels and top lights', 'Smart locks (selected ranges)', 'Chrome, black, gold or graphite hardware', 'House numbers and knockers'],
    faqs: [
      ['Are composite doors better than uPVC doors?', 'Composite doors are thicker, usually feel more solid, insulate slightly better and look more like timber. uPVC doors cost less. Both can be very secure when correctly specified and fitted. Our <a href="/guides/upvc-vs-composite-doors/">uPVC vs composite guide</a> compares them in detail.'],
      ['How long does a composite door take?', 'Composite doors are made to order after the survey, so the lead time depends on the range and colour. We confirm it on your quote.'],
      ['Will a composite door fade?', 'GRP skins are made to resist UV, but any finish can change slightly over many years in full sun. Wash the door with mild soapy water a few times a year and avoid abrasive cleaners and solvents.'],
    ],
    related: ['upvc-doors', 'stable-doors', 'flush-casement-windows'],
  },
  {
    slug: 'french-doors',
    tag: "Garden access",
    chips: ["No centre post", "Shoot bolts"],
    category: 'doors',
    name: 'French doors',
    short: 'A pair of glazed doors with no centre post. Opens wide onto the garden.',
    metaDescription: 'uPVC French doors for gardens and patios. Opening outwards or inwards, with a multipoint lock, shoot bolts and side panels for wider openings. Free survey.',
    lead: 'French doors are a pair of glazed doors that open from the centre with no post between them, giving a wide opening onto the garden. As a rough guide they suit openings from about 1,200 mm to 1,800 mm wide. Side panels can make up the width in a larger opening.',
    body: [
      'One leaf is the main door, with the handle and multipoint lock. The other is the secondary leaf, held by shoot bolts into the head and threshold. Open the main leaf on its own for everyday use, or both for a wide opening.',
      'Most French doors open outwards, which keeps the room clear for furniture. Inward-opening doors need clear floor space and careful threshold detailing to keep rain out. Opening stays hold the doors back in the wind and protect the hinges.',
      'Approved Document K treats glass in a door as a critical location up to 1,500 mm above the floor, so French doors use toughened or laminated safety glass. Replacement doors also have to meet Part L. For doors more than 60% glazed, that means a U-value of 1.4 W/m²K or better, or a Door Set Energy Rating of band C or above.',
    ],
    features: [
      ['Wide clear opening', 'No centre post when both doors are open.'],
      ['Secure secondary leaf', 'Shoot bolts lock into the head and threshold.'],
      ['Opening stays', 'Hold the doors open and protect the hinges in the wind.'],
      ['Side panels', 'Extend the glass across wider openings.'],
    ],
    specs: [['Opening', 'Outward or inward'], ['Security', 'Multipoint lock, shoot bolts, anti-snap cylinder'], ['Glass', 'Toughened or laminated safety glass, A-rated options'], ['Energy', 'Meets Part L for replacement doors (1.4 W/m²K or better, or DSER band C or above where more than 60% glazed)'], ['Threshold', 'Standard or low threshold']],
    goodFor: ['Garden rooms and extensions', 'Replacing patio doors', 'Openings up to about 1.8 m'],
    options: ['Side panels', 'Georgian bars', 'Low threshold', 'Integral blinds', 'Opening stays'],
    faqs: [
      ['French doors or patio doors?', 'French doors open the full width and suit narrower openings, but they need space to swing. <a href="/doors/patio-doors/">Sliding patio doors</a> suit wider openings and need no swing space, but only part of the width opens at once. We can show you both at survey.'],
      ['Should French doors open in or out?', 'Outward opening is the usual choice, because the doors take up no room inside. Inward opening suits a Juliet balcony, or a small patio where outward doors would block the path. Inward doors need extra care at the threshold to keep rain out.'],
      ['Can I widen my opening for French doors?', 'Often, but widening an opening means a new lintel. That is structural work, and it needs Building Regulations approval. We can advise at survey and size the doors to the opening you settle on.'],
    ],
    related: ['patio-doors', 'bifold-doors', 'tilt-and-turn-windows'],
  },
  {
    slug: 'patio-doors',
    tag: "Wide openings",
    chips: ["2–4 panels", "Anti-lift locks"],
    category: 'doors',
    name: 'Sliding patio doors',
    short: 'Large glass panels that slide on tandem rollers. No space needed for doors to swing.',
    metaDescription: 'uPVC in-line sliding patio doors with large glass panels, tandem rollers and anti-lift multipoint locking. 2, 3 and 4 panel layouts. Free survey and quote.',
    lead: 'In-line sliding patio doors use large glazed panels that slide past each other on tandem rollers. You get a wide view and easy access without needing room for doors to swing, which helps where furniture sits close to the glass.',
    body: [
      'Two-panel doors are the most common. Three- and four-panel layouts suit wider openings, with one or two sliding panels. Multipoint hook locks and anti-lift blocks stop a sliding panel being lifted off its track.',
      'The trade-off is that only part of the width opens at any time, roughly half on a two-panel door. If you want the whole wall open in summer, look at <a href="/doors/bifold-doors/">bi-fold doors</a>. If you want a clear view and a door that is simple to use every day, a slider is the easier choice.',
      'Rollers and tracks wear over the years. If your existing patio door has become heavy to slide, look at our <a href="/repairs/patio-and-bifold-repairs/">patio and bi-fold door repairs</a> first. New rollers often fix it for much less than the cost of a new door.',
    ],
    features: [
      ['Big glass, slim frames', 'More view and less frame.'],
      ['Tandem rollers', 'Paired rollers spread the weight of each panel so it slides easily.'],
      ['Anti-lift security', 'Hook locks and anti-lift blocks keep panels on the track.'],
      ['No swing space', 'Furniture can sit close to the glass.'],
    ],
    specs: [['Configurations', '2-, 3- and 4-panel'], ['Security', 'Multipoint hook locking, anti-lift blocks'], ['Glass', 'Toughened safety glass, A-rated options'], ['Energy', 'Meets Part L for replacement doors (1.4 W/m²K or better, or DSER band C or above where more than 60% glazed)'], ['Colours', 'White, woodgrain and RAL colours']],
    goodFor: ['Wide openings', 'Rooms with furniture near the doors', 'Replacing old aluminium patio doors'],
    options: ['3- and 4-panel layouts', 'Low threshold', 'Child-safety lock'],
    faqs: [
      ['Can you repair my existing patio door instead?', 'Often, yes. Worn rollers, damaged tracks and failed locks can usually be replaced. See our <a href="/repairs/patio-and-bifold-repairs/">patio and bi-fold door repairs</a> page.'],
      ['Patio doors or bi-folds?', 'Sliding patio doors give more glass and less frame, and they are simpler to use day to day. Bi-folds open almost the whole width, but there are more frames in the view when they are closed and the panels need space to stack. Think about how often you will open the full width.'],
    ],
    related: ['french-doors', 'bifold-doors', 'sliding-windows'],
  },
  {
    slug: 'bifold-doors',
    tag: "Whole-wall opening",
    chips: ["Traffic door", "Low threshold"],
    category: 'doors',
    name: 'Bi-fold doors',
    short: 'Panels that fold and stack to open almost a whole wall. A traffic door for daily use.',
    metaDescription: 'uPVC bi-fold doors for extensions and garden rooms. Panels fold to one or both sides, with a traffic door for daily use and low threshold options. Free survey.',
    lead: 'Bi-fold doors are a run of hinged panels that fold concertina-style and stack to one or both sides, opening almost the full width of the frame. A traffic door lets you use one panel as an everyday door without folding the rest.',
    body: [
      'uPVC bi-folds are an affordable way to open up an extension. They do have thicker frames than aluminium, and there are limits on panel size. For very wide openings, or where you want the slimmest sightlines, aluminium bi-folds may suit better. We will tell you which fits your opening and budget.',
      'Bi-folds need a level, square structural opening and a properly supported head, because any sag stops the panels folding smoothly. We check both at survey. Think too about where the stacked panels will sit. Folding outwards keeps the room clear, but the stack needs space on the patio.',
      'Approved Document K treats glass in a door as a critical location up to 1,500 mm above the floor, so bi-folds use toughened safety glass. Replacement bi-folds also need to meet Part L, which for doors more than 60% glazed means a U-value of 1.4 W/m²K or better, or a Door Set Energy Rating of band C or above.',
    ],
    features: [
      ['Wide opening', 'Panels stack neatly to open almost the full width.'],
      ['Traffic door', 'One panel works as a normal door day to day.'],
      ['Fold in or out', 'Choose the direction and stacking side to suit your space.'],
      ['Low threshold', 'Options for a near-flush step onto the patio.'],
    ],
    specs: [['Configurations', '2 to 6 panels, stacking left, right or split'], ['Security', 'Multipoint locking, shoot bolts on each panel'], ['Glass', 'Toughened safety glass, A-rated options'], ['Energy', 'Meets Part L for replacement doors (1.4 W/m²K or better, or DSER band C or above where more than 60% glazed)'], ['Threshold', 'Standard or low threshold']],
    goodFor: ['Kitchen and living extensions', 'Garden rooms', 'Openings around 2–4 m wide'],
    options: ['Traffic door', 'Low threshold', 'Integral blinds', 'Dual colour'],
    faqs: [
      ['How many panels do I need?', 'It depends on the width of the opening and how you want the panels to stack. As a guide, panels are usually about 600 mm to 900 mm wide. With an odd number of panels, one end panel can work as a traffic door while the rest stack to one side. We draw the options at survey.'],
      ['Do bi-fold doors let in draughts?', 'They should not if the opening is square and the doors are adjusted correctly. Draughts and leaks usually point to a sagging head, an uneven threshold or panels that have dropped, and these can often be put right. See our <a href="/repairs/patio-and-bifold-repairs/">patio and bi-fold door repairs</a>.'],
    ],
    related: ['patio-doors', 'french-doors', 'composite-doors'],
  },
  {
    slug: 'stable-doors',
    tag: "Kitchens & cottages",
    chips: ["Split leaves", "Both leaves lock"],
    category: 'doors',
    name: 'Stable doors',
    short: 'A door split into top and bottom leaves. Fresh air in, children and pets kept in.',
    metaDescription: 'uPVC and composite stable doors with top and bottom leaves that open together or separately. Multipoint locking on both leaves. Free survey and written quote.',
    lead: 'A stable door is split horizontally into two leaves that open together as one door or separately. Open the top for fresh air and light while the bottom keeps children and pets inside. It is a long-standing favourite for kitchens and cottages.',
    body: [
      'Each leaf has its own locking, and the two are joined together when closed, so a stable door is as secure as a standard entrance door when correctly specified. Ask how the leaves connect and how many keys you will need, because this varies between systems.',
      'The meeting rail between the leaves is rebated and has a weather bar to keep rain out. It is still an extra joint compared with a one-piece door, so on a very exposed wall we check the position and the drip detail at survey.',
      'Any glass in the top leaf is toughened or laminated safety glass, as Approved Document K requires for doors. Like any replacement door, a stable door must also meet Part L, with a U-value of 1.4 W/m²K or better, or a Door Set Energy Rating of band B or above.',
    ],
    features: [
      ['Two independent leaves', 'Open the top, the bottom or both together.'],
      ['Locking on both leaves', 'Multipoint locking on each leaf, joined when closed.'],
      ['Weather-sealed', 'A rebated meeting rail with a weather bar.'],
      ['uPVC or composite', 'Available in both constructions.'],
    ],
    specs: [['Construction', 'uPVC or composite'], ['Security', 'Multipoint lock to each leaf, anti-snap cylinder'], ['Glass', 'Optional glazed top leaf in safety glass'], ['Energy', 'Meets Part L for replacement doors (1.4 W/m²K or better, or DSER band B or above)'], ['Colours', 'White, woodgrain and RAL colours']],
    goodFor: ['Kitchen and utility doors', 'Cottages and farmhouses', 'Homes with pets or young children'],
    options: ['Glazed top leaf', 'Letterplate', 'Low threshold'],
    faqs: [
      ['Is a stable door secure?', 'Yes, when both leaves have their own multipoint locking and are secured together when closed. We specify this as standard.'],
      ['Will I need two keys?', 'It depends on the system. Some use a separate cylinder for each leaf, others lock both leaves from one. We confirm the arrangement on your quote.'],
      ['Can a stable door be my front door?', 'It can, and it suits many cottages. Check that the door meets any security standard your insurer asks for, and decide where the letterplate goes, usually in the bottom leaf.'],
    ],
    related: ['upvc-doors', 'composite-doors', 'french-doors'],
  },
];

export const categories = {
  windows: {
    name: 'Windows',
    title: 'uPVC windows',
    metaDescription: 'Made-to-measure uPVC windows, supplied and fitted. Casement, flush casement, tilt & turn, sash, bay and bow, sliding and shaped styles. Free survey and quote.',
    lead: 'Every window is made to measure from our survey and specified to current Building Regulations for energy, ventilation, safety glass and escape. Choose a style to see how it opens and where it suits.',
  },
  doors: {
    name: 'Doors',
    title: 'uPVC & composite doors',
    metaDescription: 'uPVC and composite front doors, French doors, sliding patio doors, bi-folds and stable doors. Multipoint locks and anti-snap cylinders. Free survey and quote.',
    lead: 'Front and back doors, garden doors and stable doors, with multipoint locks, anti-snap cylinders and safety glass as standard.',
  },
};

export const colours = [
  { name: 'White', hex: '#F4F4F1' },
  { name: 'Cream', hex: '#EDE6CF' },
  { name: 'Agate grey', hex: '#B4B2AA' },
  { name: 'Anthracite grey · RAL 7016', hex: '#383E42' },
  { name: 'Black', hex: '#1E1F21' },
  { name: 'Chartwell green', hex: '#8FA592' },
  { name: 'Golden oak', hex: '#A8692D' },
  { name: 'Rosewood', hex: '#5B2A22' },
];
